spring.application.name=libraryManagement

# mySQL connect
spring.datasource.url=jdbc:mysql://localhost:3306/librarymanagement
spring.datasource.username=root
spring.datasource.password=Divyesh@2108
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



logging.level.org.springframework.data.jpa.repository=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
# Swagger Configuration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true